import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = resolve(__dirname, '..')
const langDir = resolve(rootDir, 'src', 'lang')
const outputFile = resolve(rootDir, 'src', 'locales-data.ts')

interface LocaleMap {
  [key: string]: string
}

interface AllLocales {
  [localeCode: string]: LocaleMap
}

function parseLine(line: string): [string, string] {
  var eqIdx = line.indexOf('=')
  if (eqIdx === -1) {
    return [line, '']
  }
  return [line.substring(0, eqIdx), line.substring(eqIdx + 1)]
}

function fileNameToLocale(fileName: string): string {
  var mapping: Record<string, string> = {
    USER_ZH: 'zh-CN',
    USER_TW: 'zh-TW',
    USER_EN: 'en',
    USER_PT: 'pt'
  }
  var base = fileName.replace(/\.txt$/, '')
  return mapping[base] || base
}

function readLocaleFile(filePath: string): { keys: string[]; map: LocaleMap } {
  var content = readFileSync(filePath, 'utf-8')
  var lines = content.split(/\r?\n/)
  var keys: string[] = []
  var map: LocaleMap = {}

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i]
    if (line === '') continue
    var parsed = parseLine(line)
    var key = parsed[0]
    var value = parsed[1]
    keys.push(key)
    map[key] = value
  }

  return { keys: keys, map: map }
}

function deduplicateKeys(keys: string[]): string[] {
  var seen: Record<string, boolean> = {}
  var result: string[] = []
  for (var i = 0; i < keys.length; i++) {
    var k = keys[i]
    if (!seen[k]) {
      seen[k] = true
      result.push(k)
    }
  }
  return result
}

function alignAllKeys(locales: Record<string, { keys: string[]; map: LocaleMap }>): string[] {
  var orderedKeys: string[] = []
  var localeNames = Object.keys(locales)

  var zhKeys = locales['zh-CN'] ? locales['zh-CN'].keys : []
  if (zhKeys.length === 0 && localeNames.length > 0) {
    zhKeys = locales[localeNames[0]].keys
  }
  orderedKeys = deduplicateKeys(zhKeys.slice())

  for (var i = 0; i < localeNames.length; i++) {
    var loc = locales[localeNames[i]]
    for (var j = 0; j < loc.keys.length; j++) {
      var k = loc.keys[j]
      if (orderedKeys.indexOf(k) === -1) {
        orderedKeys.push(k)
      }
    }
  }

  return orderedKeys
}

function buildAlignedLocales(
  locales: Record<string, { keys: string[]; map: LocaleMap }>,
  allKeys: string[]
): AllLocales {
  var result: AllLocales = {}
  var localeNames = Object.keys(locales)

  for (var i = 0; i < localeNames.length; i++) {
    var locName = localeNames[i]
    var locMap = locales[locName].map
    var alignedMap: LocaleMap = {}

    for (var j = 0; j < allKeys.length; j++) {
      var key = allKeys[j]
      alignedMap[key] = key in locMap ? locMap[key] : ''
    }

    result[locName] = alignedMap
  }

  return result
}

function generateTypeScript(allLocales: AllLocales): string {
  var sb: string[] = []
  sb.push('// AUTO-GENERATED by scripts/build.ts. DO NOT EDIT.')
  sb.push('')

  var localeNames = Object.keys(allLocales)
  for (var i = 0; i < localeNames.length; i++) {
    var locName = localeNames[i]
    var locMap = allLocales[locName]
    var keys = Object.keys(locMap)

    sb.push('var ' + locName.replace(/-/g, '_') + 'Map: Record<string, string> = {')
    for (var j = 0; j < keys.length; j++) {
      var key = keys[j]
      var value = locMap[key]
      var escapedValue = value
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
      sb.push("  '" + key + "': '" + escapedValue + "',")
    }
    sb.push('}')
    sb.push('')
  }

  sb.push('export var localesData: Record<string, Record<string, string>> = {')
  for (var k = 0; k < localeNames.length; k++) {
    var ln = localeNames[k]
    sb.push("  '" + ln + "': " + ln.replace(/-/g, '_') + 'Map,')
  }
  sb.push('}')
  sb.push('')

  return sb.join('\n')
}

console.log('[build] Reading language files from:', langDir)

var files = readdirSync(langDir).filter(function (f) { return f.endsWith('.txt') })
var rawLocales: Record<string, { keys: string[]; map: LocaleMap }> = {}

for (var i = 0; i < files.length; i++) {
  var file = files[i]
  var localeCode = fileNameToLocale(file)
  var filePath = resolve(langDir, file)
  var data = readLocaleFile(filePath)
  rawLocales[localeCode] = data
  console.log('  ' + localeCode + ': ' + Object.keys(data.map).length + ' keys')
}

var allKeys = alignAllKeys(rawLocales)
console.log('[build] Total unique keys:', allKeys.length)

var aligned = buildAlignedLocales(rawLocales, allKeys)
var tsContent = generateTypeScript(aligned)
writeFileSync(outputFile, tsContent, 'utf-8')
console.log('[build] Generated:', outputFile)

console.log('[build] Building proxy (npm package)...')
execSync('npx tsup', { cwd: rootDir, stdio: 'inherit' })

console.log('[build] Building runtime (UMD for CDN)...')
execSync('npx tsup --config tsup.runtime.config.ts', { cwd: rootDir, stdio: 'inherit' })

var iifeFile = resolve(rootDir, 'dist', 'h5-cc-i18n.min.js')
var iifeCode = readFileSync(iifeFile, 'utf-8')
var umdWrapper = [
  '(function(root,factory){',
  "if(typeof define==='function'&&define.amd){define([],factory)}",
  "else if(typeof module==='object'&&module.exports){module.exports=factory()}",
  "else{root.__H5_CC_I18N__=factory()}",
  "}(typeof self!=='undefined'?self:this,function(){",
  iifeCode,
  'return __i18nRuntimeInstance && __i18nRuntimeInstance.default;',
  '}));'
].join('')
writeFileSync(iifeFile, umdWrapper, 'utf-8')
console.log('[build] UMD output:', iifeFile)

console.log('[build] Building runtime (ESM/CJS for bundling)...')
execSync('npx tsup --config tsup.runtime.esm.config.ts', { cwd: rootDir, stdio: 'inherit' })

console.log('[build] Done!')
